### PR TITLE
ok i think i figured out pull request

### PR DESCRIPTION
**Pull request by mattb61**
im just posting this to see if this works

edit: it looks like it did., you can see my Commit. now to figure out how to allow you to see/edit them, if you can't.

edit 2: figured it out.

### CODE REVIEW

**Comment by Alexander-Moyles** [comment]
Looks alright thus far, make sure to add the main file that will actually utilize the classes, also worth noting that before the project is submitted that all the classes should be moved into the same file - but we'll handle that later.

**Review by Alexander-Moyles — APPROVED** [review]

**Comment by mattb61** [comment]
I finally managed to get the data into PyCharm. I don't have the main file for utilizing the Class yet because I have no idea how to make objects from a list in a Class file yet. Once I figure that out (hopefully) the rest shouldn't take long.

**Comment by Alexander-Moyles** [comment]
To put list items into an object just have the code put list items as the object attributes.

Example: object(attribute1, attribute2) => object(list[0], list[1])

**Comment by Alexander-Moyles** [comment]
Made some changes to your code, it doesn't quite work yet but should be a lot closer to what you need.

**Pull request merged**
